# Generated by Django 4.1.1 on 2022-09-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_elespectador_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elespectador',
            name='date',
            field=models.DateField(max_length=100),
        ),
    ]
