# Generated by Django 4.1.1 on 2022-09-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_elespectador_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elespectador',
            name='date',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
